# Reference: https://github.com/i3/i3/blob/next/etc/config

start-at-login = true
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
#accordian-padding = 50
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'

[mode.main.binding]
alt-enter = 'exec-and-forget open -n /etc/profiles/per-user/mobrienv/bin/alacritty'

alt-h = 'focus right'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

alt-shift-h= 'move-through left'
alt-shift-j = 'move-through down'
alt-shift-k = 'move-through right'
alt-shift-l = 'move-through left'

alt-f = [
  'layout floating tiling',
  'mode main'
]
alt-space = ['fullscreen']
alt-w = 'layout h_accordion'
alt-comma = 'layout v_accordion'
alt-period = 'layout tiles horizontal vertical'
alt-shift-space = 'layout floating tiling' # 'floating toggle' in i3

alt-shift-minus = 'resize smart -50'
alt-shift-equal = 'resize smart +50'

alt-0 = 'workspace 0'
alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-n = 'workspace N'
alt-t = 'workspace T'
alt-c = 'workspace C'
alt-b = 'workspace B'
alt-s = 'workspace S'


alt-shift-0 = 'move-node-to-workspace 0'
alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-n = 'move-node-to-workspace N'
alt-shift-t = 'move-node-to-workspace T'
alt-shift-c = 'move-node-to-workspace C'
alt-shift-b = 'move-node-to-workspace B'
alt-shift-s = 'move-node-to-workspace S'
alt-shift-w = 'move-node-to-workspace W'

alt-tab = 'workspace-back-and-forth'
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

alt-shift-period = 'mode service'
alt-r = 'mode resize'
alt-shift-r = 'reload-config'

[mode.service.binding]
r = ['flatten-workspace-tree', 'mode main']                # reset layout
backspace = ['close-all-windows-but-current', 'mode main']
esc = ['reload-config', 'mode main']

[mode.resize.binding]
h = 'resize width -50'
j = 'resize height +50'
k = 'resize height -50'
l = 'resize width +50'
enter = 'mode main'
esc = 'mode main'

[[on-window-detected]]
check-further-callbacks = true
run = 'move-node-to-workspace 1'
if.during-aerospace-startup = true

# Floating
[[on-window-detected]]
if.app-name-regex-substring = 'Finder'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'Bitwarden'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'Chime'
run = 'layout floating'

# B - Browser - workspace
[[on-window-detected]]
if.app-name-regex-substring = 'Firefox'
run = 'move-node-to-workspace B'

# E - Editor workspace
[[on-window-detected]]
if.app-name-regex-substring = 'Code'
run = 'move-node-to-workspace E'

[[on-window-detected]]
if.app-name-regex-substring = 'IntelliJ'
run = 'move-node-to-workspace E'

# N - Notes workspace
[[on-window-detected]]
if.app-name-regex-substring = 'Obsidian'
run = 'move-node-to-workspace N'

# T - Terminal workspace
[[on-window-detected]]
if.app-name-regex-substring = 'Alacritty'
run = 'move-node-to-workspace T'

[[on-window-detected]]
if.app-name-regex-substring = 'iTerm2'
run = 'move-node-to-workspace T'


# S - Social
[[on-window-detected]]
if.app-name-regex-substring = 'Outlook'
run = 'move-node-to-workspace S'

[[on-window-detected]]
if.app-name-regex-substring = 'Slack'
run = 'move-node-to-workspace S'

